comoxo_farm/urls.py
from django.urls import path
from django.conf.urls import url

from comoxo_farm import views

app_name = 'comoxo_farm'
urlpatterns = [
    path('', views.home_page, name='comoxo'),
    
]

comoxo_organics/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls.conf import include
from comoxo_farm.views import home_page 
from conga_house.views import conga_page
from users.views import sign_in

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name='home'),
    path('comoxo/', include(('comoxo_farm.urls', 'home_page'), namespace='comoxo_farm')),
    path('conga/', include(('conga_house.urls', 'conga_page'), namespace='conga_house')),
    path('users/', include(('users.urls', 'dashboard'), namespace='users')),
    path('signin', sign_in, name='sign_in')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

conga_house/urls.py
from django.urls import path
from django.conf.urls import url
from conga_house import views

app_name = 'conga_house'
urlpatterns = [
    path('', views.conga_page, name='conga_page'),
    
]

users/urls.py
from django.urls import path
from django.conf.urls import url

from users import views

app_name = 'users'
urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('signout/', views.sign_out, name='sign_out'),
    path('signin/', views.sign_in, name='sign_in'),
    path('review/add', views.review_add, name='review_add'),
    path('review/update', views.review_update, name='review_update'),
    path('thanks/', views.thank_you, name='thank_you'),
    
]

users/models.py
from datetime import timedelta
from django.db import models
from django_countries.fields import CountryField
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from .managers import CustomUserManager
from django.conf import settings
from django.dispatch import receiver
from django.db.models.signals import post_save

STATUS = ((0, "Not Approved"), (1, "Approved"))
LOCATIONS = ((0, "Unknown"), (1, "Comoxo"), (2, "Conga"))
STARS = ((1, "Horrible"), (2, "Unsatisfied"),(3, "Neutral"),(4, "Good"),(5, "Excellent"))

TODAY = timezone.now()

def return_date_time_now():
    now = timezone.now()
    return now

def return_date_time_weeks():
    now = timezone.now()
    return now + timedelta(14)

def return_min_age():
    now = timezone.now()
    return now - timedelta(18*365)


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    full_name = models.CharField(max_length=200)
    country = CountryField()
    birthdate = models.DateField(blank=True, default=return_min_age)
    start_date = models.DateField(default=return_date_time_now)
    end_date = models.DateField(default=return_date_time_weeks)
    details = models.TextField(default="blank")
    location = models.IntegerField(choices=LOCATIONS, default=0)
    status = models.IntegerField(choices=STATUS, default=0)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email
        
    class Meta:
        app_label = 'users'


class Reviews(models.Model):
    title = models.CharField(max_length=200, unique=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE, related_name="user_review")
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    rating = models.IntegerField(choices=STARS, default=0)
    status = models.IntegerField(choices=STATUS, default=0)
    created_on = models.DateTimeField(auto_now_add=True)
    location = models.IntegerField(choices=LOCATIONS, default=0)
    pic = models.ImageField(blank=True, null=True, upload_to='reviews', default="https://i.stack.imgur.com/y9DpT.jpg")

    def __str__(self):
        return "Review by {} from {}".format(self.author, self.author.country)

users/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser, Reviews


class DateInput(forms.DateInput):
    input_type = 'date'

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('email', 'password1', 'password2', 'full_name', 'country', 'birthdate', 'start_date', 'end_date', 'details',)
        widgets = {
            'birthdate': DateInput(),
            'start_date': DateInput(),
            'end_date': DateInput()
            }

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('start_date', 'end_date', 'details')

class ReviewForm(ModelForm):
    class Meta:
        model = Reviews
        fields = ('title', 'content', 'rating','pic')

users/views.py
from django.contrib.auth.models import User
from django.shortcuts import redirect, render, get_object_or_404
from .models import CustomUser, Reviews
from .forms import CustomUserCreationForm, CustomUserChangeForm, ReviewForm
from django.contrib.auth.forms import AuthenticationForm
from django.db import IntegrityError
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required


@login_required
def dashboard(request):
    user = request.user
    if user.status == 1:
        return redirect("users:review_add")
    else:
        if request.method == 'POST':
            form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
            if form.is_valid():
                form.save()
                return render(request, 'users/home.html', {'form':CustomUserChangeForm(), 'success':'Your changes has been saved.',})
            else:
                return render(request, 'users/home.html', {'form':CustomUserChangeForm(), 'error':'Your changes has not been saved.',})
        else:
            return render(request, 'users/home.html', {'form':CustomUserChangeForm()})

@login_required
def review_add(request):
    already_reviewed = Reviews.objects.filter(author=request.user).count()
    if already_reviewed >= 1:
        return redirect("users:review_update")
    else:
        print(already_reviewed)
        if request.method == 'GET':
            return render(request, 'users/review_add.html', {'form':ReviewForm()})
        else:
            try:
                form = ReviewForm(request.POST, request.FILES)
                new_review = form.save(commit=False)
                new_review.author = request.user
                new_review.save()
                return render(request, 'users/home.html', {'form':ReviewForm(), 'success':'Your review has been added'})
            except ValueError:
                return render(request, 'users/review_add.html', {'form':ReviewForm(), 'error':'Bad data passed in. Try again.'})

@login_required
def review_update(request):
    review_approved = Reviews.objects.filter(author=request.user, status=1).count()
    last_review = Reviews.objects.all()[:1]
    last_review_item = get_object_or_404(Reviews, author=request.user)
    if review_approved == 1:
        return redirect("users:thank_you")
    else:
        if request.method == 'GET':
            return render(request, 'users/review_update.html', {'form':ReviewForm(),'last_review':last_review})
        else:
            try:
                form = ReviewForm(request.POST, request.FILES, )
                edit_review = form.save(commit=False)
                edit_review.author = request.user
                edit_review.save()
                return render(request, 'users/review_update.html', {'form':ReviewForm(), 'last_review':last_review, 'success':'Your review has been added'})
            except ValueError:
                return render(request, 'users/review_update.html', {'form':ReviewForm(), 'last_review':last_review, 'error':'Bad data passed in. Try again.'})

@login_required
def thank_you(request):
    return render(request,'users/thank_you.html')

@login_required
def sign_out(request):
    if request.method == 'POST':
        logout(request)
        return redirect('users:sign_in')

def sign_in(request):
    if request.method == 'GET':
        return render(request, 'users/sign_in.html', {'form':AuthenticationForm()})
    else:
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, 'users/sign_in.html', {'form':AuthenticationForm(), 'error':'Username and password did not match'})
        else:
            login(request, user)
            return redirect('users:dashboard')

users/templates/users/base.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
<html lang="en">
	<head>
		<title>Comoxo Organics | Visitors </title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<style>
			div#hidden{display:none!Important;}
		</style>
		<link href="https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900" rel="stylesheet">
		<link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/animate.css' %}">
		<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
		<link rel="stylesheet" href="{% static 'css/aos.css' %}">
		<link rel="stylesheet" href="{% static 'css/style.css' %}" />
		<script src="https://kit.fontawesome.com/923da19769.js" crossorigin="anonymous"></script>
	</head>
	<body>
		<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark" id="ftco-navbar">
			<div class="container">
				<a class="navbar-brand" href="{% url 'comoxo_farm:comoxo' %}"><span>Comoxo</span></a>
				<button class="navbar-toggler js-fh5co-nav-toggle fh5co-nav-toggle" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
				<i class="fa fa-bars"></i> Menu
				</button>
				<div class="collapse navbar-collapse" id="ftco-nav">
					<ul class="navbar-nav nav ml-auto">
						<li class="nav-item"><a href="{% url 'comoxo_farm:comoxo' %}" class="nav-link"><span>Comoxo Farm</span></a></li>
						<li class="nav-item"><a href="{% url 'conga_house:conga_page' %}" class="nav-link" ><span>La Conga House</span></a></li>
						<li class="nav-item cta"><a href="#" onclick="$('#signOutBtn').click()" class="nav-link">Log Out</a></li>
						<form style='display: none;' method="POST" action="{% url 'users:sign_out' %}">
							{% csrf_token %}
							<button id="signOutBtn" type="submit">Sign Out</button>
						</form>
					</ul>
				</div>
			</div>
		</nav>
		<!-- Start: Main Content -->
		{% block content %}
		{% endblock content %}
		<!-- End: Main Content -->
		<footer class="ftco-footer ftco-section">
			<div class="container">
				<div class="row mb-5">
					<div class="col-md-8">
						<div class="ftco-footer-widget mb-4">
							<h2 class="ftco-heading-2">Comoxo Organics</h2>
							<p>Comoxo Organics is a family-run business since 1983. We not only offer high-grade kiwi in Galicia, but also
								variety of fruits and vegetables depending on the season.
							</p>
							<ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
								<li class="ftco-animate"><a href="https://instagram.com/comoxoorganics"><span class="icon-instagram"></span></a></li>
							</ul>
						</div>
					</div>
					<div class="col-md-4">
						<div class="ftco-footer-widget mb-4 ml-md-4">
							<h2 class="ftco-heading-2">Links</h2>
							<ul class="list-unstyled">
								<li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Comoxo Organics</a></li>
								<li><a href="#"><span class="icon-long-arrow-right mr-2"></span>La Conga House</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12 text-center">
					Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | Comoxo Organics</p>
				</div>
			</div>
			</div>
		</footer>
		<!-- loader -->
		<div id="ftco-loader" class="show fullscreen">
			<svg class="circular" width="48px" height="48px">
				<circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
				<circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/>
			</svg>
		</div>
		<script src="{% static 'js/jquery.min.js' %}"></script>
		<script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
		<script src="{% static 'js/popper.min.js' %}"></script>
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
		<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
		<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
		<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
		<script src="{% static 'js/owl.carousel.min.js' %}"></script>
		<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
		<script src="{% static 'js/aos.js' %}"></script>
		<script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
		<script src="{% static 'js/scrollax.min.js' %}"></script>
		<script src="{% static 'js/main.js' %}"></script>
	</body>
</html>

users/templates/users/home.html
{% extends 'users/base.html' %}
{% block content %}
<section class="ftco-section">
	<div class="container">
	<div class="row ftco-animate">

		<div class="col-lg-9 order-lg-last ftco-animate">
			<h2 class="mb-3">Hey {{ user.full_name | truncatewords:1 }} Your request is still pending!</h2>
			<p>In the mean time, if you wish to make changes or add additional details, update the form below.
			</p>
			{% if error %}
			<div class="alert alert-danger" role="alert">{{ error }}</div>
			{% endif %}
			{% if success %}
			<div class="alert alert-success" role="alert">{{ success }}</div>
			{% endif %}
			<form method="post" class="contact-form">
				{% csrf_token %}
				<div class="row">
					<div class="col-lg-6 col-md-6 col-xs-12">
						<div id="id_start_date" class="form-group">
							<label for="id_start_date">Start Date<span class="asteriskField">*</span></label> 
							<input type="date" name="start_date" value="{{user.start_date|date:"Y-m-d"}}" class="form-control" required />
						</div>
					</div>
					<div class="col-lg-6 col-md-6 col-xs-12">
						<div id="id_start_date" class="form-group">
							<label for="id_end_date">End Date<span class="asteriskField">*</span></label> 
							<input type="date" name="end_date" value="{{user.end_date|date:"Y-m-d"}}" class="form-control" required />
						</div>
					</div>
				</div>
				<div id="id_details" class="form-group">
					<label for="id_details">Details of Your Visit <span class="asteriskField">*</span></label> 
					<textarea name="details" cols="40" rows="5" class="textarea form-control" required id="id_details">{{ user.details }}</textarea> 
				</div>
				<button type="submit" class="btn btn-lg btn-primary">Save Changes</button>
			</form>
		</div>
	</div>
</section>
{% endblock content %}

users/templates/users/review_add.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<section class="ftco-section">
	<div class="container">
	<div class="row ftco-animate">
	<h2 class="mb-3">Hey {{ user.full_name | truncatewords:1 }} How was your stay at
		{% if user.location == 0 %} Comoxo and Conga? {% endif %}
		{% if user.location == 1 %} Comoxo? {% endif %}
		{% if user.location == 2 %} Conga House? {% endif %}    
	</h2>
	{% if error %}<div class="alert alert-danger" role="alert">{{ error }}</div>{% endif %}
    <div class="col-lg-8 order-lg-last ftco-animate">
	<form method="post" enctype="multipart/form-data">
        {% csrf_token %}
		<div class="row">
			<div class="col-md-12">
				<div class="form-group">
					<label for="id_details">Title</label> 
					<input type="text" name="title" class="form-control" required />
				</div>
            </div>
			<div class="col-md-12">
				<div id="id_details" class="form-group">
					<label>Your Review</label> 
					<textarea name="content" cols="40" rows="5" class="textarea form-control" required></textarea> 
				</div>
            </div>
			<div class="col-md-6 col-xs-12">
				<div class="form-group">
					<label>Upload a photo</label> 
					<input type="file" name="pic" class="form-control" />
				</div>
			</div>
			<div class="col-md-6 col-xs-12">
				<div class="form-group">
				<label>Rate Your Stay</label>
				<select class="dateinput form-control" name="rating" required>
					<option value="5" selected >⭐⭐⭐⭐⭐</option>
					<option value="4" >⭐⭐⭐⭐</option>
					<option value="3" >⭐⭐⭐</option>
					<option value="2" >⭐⭐</option>
					<option value="1" >⭐</option>
					</select>
				</div>
			</div>
            <div class="col-md-12">
			    <button type="submit" class="btn btn-lg btn-primary">Submit</button>
            </div>
        </div>
	</form>
	</div>
	</div>
	</div>
</section>
{% endblock content %}

users/templates/users/review_update.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<section class="ftco-section">
	<div class="container">
	<div class="row ftco-animate">
	<h2 class="mb-3">Hey {{ user.full_name | truncatewords:1 }} How was your stay at
		{% if user.location == 0 %} Comoxo and Conga? {% endif %}
		{% if user.location == 1 %} Comoxo? {% endif %}
		{% if user.location == 2 %} Conga House? {% endif %}    
	</h2>
	{% if error %}<div class="alert alert-danger" role="alert">{{ error }}</div>{% endif %}
    <div class="col-lg-8 order-lg-last ftco-animate">
	<form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for last_review in last_review.all %}
		<div class="row">
			<div class="col-md-12">
				<div class="form-group">
					<label for="id_details">Title</label> 
					<input type="text" name="title" class="form-control" required value="{{ last_review.title }}"/>
				</div>
            </div>
			<div class="col-md-12">
				<div id="id_details" class="form-group">
					<label>Your Review</label> 
					<textarea name="content" cols="40" rows="5" class="textarea form-control" required>{{ last_review.content }}</textarea> 
				</div>
            </div>
			<div class="col-md-6 col-xs-12">
				<div class="form-group">
					<label>Upload a photo</label> 
					<input type="file" name="pic" class="form-control"/>
                    <small>( file name: {{ last_review.pic }} )</small>
				</div>
			</div>
			<div class="col-md-6 col-xs-12">
				<div class="form-group">
				<label>Rate Your Stay</label>
				<select class="dateinput form-control" name="rating" required>
					<option value="5" selected >⭐⭐⭐⭐⭐</option>
					<option value="4" >⭐⭐⭐⭐</option>
					<option value="3" >⭐⭐⭐</option>
					<option value="2" >⭐⭐</option>
					<option value="1" >⭐</option>
					</select>
				</div>
			</div>
            {% endfor %}
            <div class="col-md-12">
			    <button type="submit" class="btn btn-lg btn-primary">Submit</button>
            </div>

        </div>
	</form>
     
	</div>
	</div>
	</div>
</section>
{% endblock content %}

users/templates/users/sign_in.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Comoxo Organics | Visitor Portal </title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<link href="https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900" rel="stylesheet">
		<link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/animate.css' %}">
		<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
		<link rel="stylesheet" href="{% static 'css/aos.css' %}">
		<link rel="stylesheet" href="{% static 'css/style.css' %}" />
		<script src="https://kit.fontawesome.com/923da19769.js" crossorigin="anonymous"></script>
	</head>
	<body>
		 <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark" id="ftco-navbar">
         <div class="container">
            <a class="navbar-brand" href="index.html"><span>Comoxo</span></a>
            <button class="navbar-toggler js-fh5co-nav-toggle fh5co-nav-toggle" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
           <i class="fa fa-bars"></i> Menu
            </button>
            <div class="collapse navbar-collapse" id="ftco-nav">
               <ul class="navbar-nav nav ml-auto">
                  <li class="nav-item"><a href="{% url 'comoxo_farm:comoxo' %}" class="nav-link"><span>Comoxo Farm</span></a></li>
                  <li class="nav-item"><a href="{% url 'conga_house:conga_page' %}" class="nav-link" ><span>La Conga House</span></a></li>                  
               </ul>
            </div>
         </div>
      </nav>
		
		<section class="ftco-section">
			<div class="container">
			<div class="row ftco-animate">
            
				<div class="col-lg-9 order-lg-last ftco-animate">
					<h2 class="mb-3">Sign in</h2>
                    {% if error %}<div class="alert alert-danger" role="alert">{{ error }}</div>{% endif %}
                        <form method="post" class="contact-form">
                            {% csrf_token %}
                            <div class="row">
                            <div class="col-lg-8 col-md-6 col-xs-12">
                                <div id="id_start_date" class="form-group">
                                    <label for="id_username">Username<span class="asteriskField">*</span></label> 
                                    <input type="email" name="username" value="" class="form-control" required />
                                </div>
                            </div>
                            
                            <div class="col-lg-8 col-md-6 col-xs-12">
                                <div id="id_start_date" class="form-group">
                                    <label for="id_password">Password<span class="asteriskField">*</span></label> 
                                    <input type="password" name="password" class="form-control" value="" required />
                                </div>
                            </div>
                            </div>
                            
                               
                            <button type="submit" class="btn btn-lg btn-primary">Save Changes</button>
                            </form>


				</div>
				
			</div>
		</section>
		<!-- .section -->
		<footer class="ftco-footer ftco-section">
      <div class="container">
      <div class="row mb-5">
      <div class="col-md-8">
      <div class="ftco-footer-widget mb-4">
      <h2 class="ftco-heading-2">Comoxo Organics</h2>
      <p>Comoxo Organics is a family-run business since 1983. We not only offer high-grade kiwi in Galicia, but also
      variety of fruits and vegetables depending on the season.</p>
      <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
      <li class="ftco-animate"><a href="https://instagram.com/comoxoorganics"><span class="icon-instagram"></span></a></li>
      </ul>
      </div>
      </div>
      <div class="col-md-4">
      <div class="ftco-footer-widget mb-4 ml-md-4">
      <h2 class="ftco-heading-2">Links</h2>
      <ul class="list-unstyled">
      <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Comoxo Organics</a></li>
      <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>La Conga House</a></li>
      </ul>
      </div>
      </div>
      </div>
      </div>
      <div class="row">
      <div class="col-md-12 text-center">
      Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | Comoxo Organics</p>
      </div>
      </div>
      </div>
      </footer>
		<!-- loader -->
		<div id="ftco-loader" class="show fullscreen">
			<svg class="circular" width="48px" height="48px">
				<circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
				<circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/>
			</svg>
		</div>
		<script src="{% static 'js/jquery.min.js' %}"></script>
		<script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
		<script src="{% static 'js/popper.min.js' %}"></script>
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
		<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
		<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
		<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
		<script src="{% static 'js/owl.carousel.min.js' %}"></script>
		<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
		<script src="{% static 'js/aos.js' %}"></script>
		<script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
		<script src="{% static 'js/scrollax.min.js' %}"></script>
		<script src="{% static 'js/main.js' %}"></script>
	</body>
</html>

users/templates/users/thank_you.html
{% extends 'users/base.html' %}
{% block content %}
<section class="ftco-section">
	<div class="container">
	<div class="row ftco-animate">

		<div class="col-lg-9 order-lg-last ftco-animate">
			<h2 class="mb-3">Hey {{ user.full_name | truncatewords:1 }} Your request is still pending!</h2>
			<p>Thank you for your stay. 
		
		</div>
	</div>
</section>
{% endblock content %}

users/templates/users/update.html
{% load crispy_forms_tags %}

<h1>Update Account</h1>
{% if error %}
    <div class="alert alert-danger" role="alert">{{ error }}</div>
{% endif %}
{% if success %}
    <div class="alert alert-success" role="alert">{{ success }}</div>
{% endif %}
{{ user.email }}
{{ user.country }}
{{ user.birthdate }}
{{ user.country }}

<form method="post">
    {% csrf_token %}
    {{ form | crispy }}
    <button type="submit" class="btn btn-primary">Save</button>
</form>